apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-orders-pvc
  namespace: cloudflow
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-csi
  resources:
    requests:
      storage: 2Gi