apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-orders-pv
  namespace: cloudflow
spec:
  capacity:
    storage: 2Gi

  accessModes:
    - ReadWriteOnce

  persistentVolumeReclaimPolicy: Retain

  storageClassName: cloudflow-local

  hostPath:
    path: /var/lib/cloudflow/postgres-orders