apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-users-pvc
  namespace: cloudflow
spec:
  accessModes:
    - ReadWriteOnce

  storageClassName: cloudflow-local

  resources:
    requests:
      storage: 2Gi