services:
  postgres-users:
    image: postgres:16
    container_name: postgres-users
    environment:
      POSTGRES_DB: cloudflow_users
      POSTGRES_USER: cloudflow
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_users_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@cloudflow.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres-users

volumes:
  postgres_users_data: