apiVersion: v1
kind: Secret
metadata:
  name: database-secret
  namespace: cloudflow
type: Opaque
stringData:
  POSTGRES_USER: cloudflow
  POSTGRES_PASSWORD: password
  DB_USER: cloudflow
  DB_PASSWORD: password