apiVersion: v1
kind: ConfigMap
metadata:
  name: order-config
  namespace: cloudflow
data:
  DB_HOST: postgres-orders
  DB_PORT: "5432"
  DB_NAME: cloudflow_orders
  RABBITMQ_URL: amqp://rabbitmq:5672