apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-orders
  namespace: cloudflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-orders
  template:
    metadata:
      labels:
        app: postgres-orders
    spec:
      containers:
        - name: postgres-orders
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: cloudflow_orders
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-orders
  namespace: cloudflow
spec:
  selector:
    app: postgres-orders
  ports:
    - port: 5432
      targetPort: 5432