apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: cloudflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: cloudflow-api-gateway:v2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3002
          envFrom:
            - configMapRef:
                name: gateway-config
          
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: cloudflow
spec:
  type: NodePort
  selector:
    app: api-gateway
  ports:
    - port: 3002
      targetPort: 3002
      nodePort: 30082